package team.epm.module.client;

import oracle.jbo.ViewObject;
import oracle.jbo.client.remote.ApplicationModuleImpl;

import team.epm.module.common.DcmModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Sun Nov 30 12:52:10 CST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DcmModuleClient extends ApplicationModuleImpl implements DcmModule {
    /**
     * This is the default constructor (do not remove).
     */
    public DcmModuleClient() {
    }

    public ViewObject getCombinationRecordView(String templateId,
                                               String combinationId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getCombinationRecordView",new String [] {"java.lang.String","java.lang.String"},new Object[] {templateId, combinationId});
        return (ViewObject)_ret;
    }

    public ViewObject getSubmitStatusVO(String sql, String templateId,
                                        String userId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getSubmitStatusVO",new String [] {"java.lang.String","java.lang.String","java.lang.String"},new Object[] {sql, templateId, userId});
        return (ViewObject)_ret;
    }
}
