package team.epm.module.client;

import oracle.jbo.Row;
import oracle.jbo.ViewObject;
import oracle.jbo.client.remote.ApplicationModuleImpl;

import team.epm.module.common.DmsModule;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jan 07 14:14:11 CST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DmsModuleClient extends ApplicationModuleImpl implements DmsModule {
    /**
     * This is the default constructor (do not remove).
     */
    public DmsModuleClient() {
    }

    public ViewObject getDmsValueView(String valueSetSrc, String valueSetId,
                                      String roleId) {
        Object _ret =
            this.riInvokeExportedMethod(this,"getDmsValueView",new String [] {"java.lang.String","java.lang.String","java.lang.String"},new Object[] {valueSetSrc, valueSetId, roleId});
        return (ViewObject)_ret;
    }
}
