package team.epm.dcm.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Jul 30 10:08:54 CST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DcmCalcParameterVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DcmCalcParameterVOImpl() {
    }
}
