package team.epm.dcm.view;

import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaRow;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Aug 13 15:00:40 CST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DcmTemplateCombinaVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DcmTemplateCombinaVOImpl() {
    }
    public void queryById(String tempId,String comId){
        ViewCriteria vc= this.createViewCriteria();
        ViewCriteriaRow vcRow = vc.createViewCriteriaRow();    
        vcRow.setAttribute("TemplateId", "='"+tempId+"'");
        vc.addElement(vcRow);
        vcRow.setAttribute("ComRecordId", "='"+comId+"'");
        vcRow.setConjunction(vcRow.VC_CONJ_AND);
        vc.addElement(vcRow);
        this.applyViewCriteria(vc);
        this.executeQuery();
        this.setApplyViewCriteriaNames(null);
    }
}
