package infa.dataintegration.ws;

import infa.dataintegration.types.DIServiceInfo;
import infa.dataintegration.types.GetWorkflowLogRequest;
import infa.dataintegration.types.Log;
import infa.dataintegration.types.LoginRequest;

import infa.dataintegration.types.SessionHeader;

import java.net.MalformedURLException;
import java.net.URL;

import javax.xml.namespace.QName;
import javax.xml.ws.Holder;
import javax.xml.ws.Service;
import javax.xml.ws.WebServiceRef;
// !THE CHANGES MADE TO THIS FILE WILL BE DESTROYED IF REGENERATED!
// This source file is generated by Oracle tools
// Contents may be subject to change
// For reporting problems, use the following
// Version = Oracle WebServices (11.1.1.0.0, build 130224.1947.04102)

public class DataIntegrationClient {

    public static void main(String[] args) throws Fault,
                                                  MalformedURLException {
        URL url = new URL("http://infa-pc:7334/wsh/services/BatchServices/DataIntegration?WSDL");
        QName qname = new QName("http://www.informatica.com/wsh","DataIntegrationService");
        Service service = Service.create(url, qname);
        DataIntegrationInterface dig = service.getPort(new QName("http://www.informatica.com/wsh","DataIntegration"), 
                                                           DataIntegrationInterface.class);
        // Add your code to call the desired methods.
        LoginRequest loginReq = new LoginRequest();
        loginReq.setRepositoryDomainName("Domain_WIN-MC4ZF6BBAT2");
        loginReq.setRepositoryName("infarp");
        loginReq.setUserName("Administrator");
        loginReq.setPassword("Administrator");

        SessionHeader sessionHeader = new SessionHeader();
        Holder<SessionHeader> Context =
            new Holder<SessionHeader>(sessionHeader);

        String str = dig.login(loginReq, Context);
        System.out.println(str);
        
        GetWorkflowLogRequest logReq = new GetWorkflowLogRequest();
        DIServiceInfo dinfo = new DIServiceInfo();
        dinfo.setDomainName("Domain_WIN-MC4ZF6BBAT2");
        dinfo.setServiceName("infais");
        logReq.setDIServiceInfo(dinfo);
        logReq.setFolderName("TEST");
        logReq.setWorkflowName("workflow");
        logReq.setTimeout(6000);
        SessionHeader sh = new SessionHeader();
        sh.setSessionId(str);
        Log log = dig.getWorkflowLog(logReq, sh);
        System.out.println("Log-->"+log.getBuffer());
    }

    public String getLogin() throws Fault, MalformedURLException {
        URL url = new URL("http://infa-pc:7334/wsh/services/BatchServices/DataIntegration?WSDL");
        QName qname = new QName("http://www.informatica.com/wsh","DataIntegrationService");
        Service service = Service.create(url, qname);
        DataIntegrationInterface dig = service.getPort(new QName("http://www.informatica.com/wsh","DataIntegration"), 
                                                           DataIntegrationInterface.class);
        // Add your code to call the desired methods.
        LoginRequest loginReq = new LoginRequest();
        loginReq.setRepositoryDomainName("Domain_WIN-MC4ZF6BBAT2");
        loginReq.setRepositoryName("infarp");
        loginReq.setUserName("Administrator");
        loginReq.setPassword("Administrator");

        SessionHeader sessionHeader = new SessionHeader();
        Holder<SessionHeader> Context =
            new Holder<SessionHeader>(sessionHeader);

        String str = dig.login(loginReq, Context);
        System.out.println(str);
        
        
        GetWorkflowLogRequest logReq = new GetWorkflowLogRequest();
        DIServiceInfo dinfo = new DIServiceInfo();
        dinfo.setDomainName("Domain_WIN-MC4ZF6BBAT2");
        dinfo.setServiceName("infais");
        logReq.setDIServiceInfo(dinfo);
        logReq.setFolderName("TEST");
        logReq.setWorkflowName("workflow");
        logReq.setTimeout(6000);
        SessionHeader sh = new SessionHeader();
        sh.setSessionId(str);
        Log log = dig.getWorkflowLog(logReq, sh);
        System.out.println("Log-->"+log.getBuffer());
        
        return str;
    }
}
