package team.epm.dcm.view.common;

import oracle.jbo.Row;
import oracle.jbo.domain.Date;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 19 17:07:15 CST 2016
// ---------------------------------------------------------------------
public interface DcmTemplateCombinationVORow extends Row {
    String getComRecordId();

    void setComRecordId(String value);

    Date getCreatedAt();

    void setCreatedAt(Date value);

    String getCreatedBy();

    void setCreatedBy(String value);

    String getId();

    void setId(String value);

    String getStatus();

    void setStatus(String value);

    String getTemplateId();

    void setTemplateId(String value);

    Date getUpdatedAt();

    void setUpdatedAt(Date value);

    String getUpdatedBy();

    void setUpdatedBy(String value);
}
