package team.epm.dms.model;

import oracle.jbo.server.EntityCache;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Oct 16 10:02:08 CST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DmsGroupCollImpl extends EntityCache {
    /**
     * This is the default constructor (do not remove).
     */
    public DmsGroupCollImpl() {
    }
}
