package team.epm.dms.model;

import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Jul 20 16:17:16 CST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DmsHtkpReturnEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Entity1 {
            public Object get(DmsHtkpReturnEOImpl obj) {
                return obj.getEntity1();
            }

            public void put(DmsHtkpReturnEOImpl obj, Object value) {
                obj.setEntity1((String)value);
            }
        }
        ,
        IndustryLine {
            public Object get(DmsHtkpReturnEOImpl obj) {
                return obj.getIndustryLine();
            }

            public void put(DmsHtkpReturnEOImpl obj, Object value) {
                obj.setIndustryLine((String)value);
            }
        }
        ,
        BusinessLine {
            public Object get(DmsHtkpReturnEOImpl obj) {
                return obj.getBusinessLine();
            }

            public void put(DmsHtkpReturnEOImpl obj, Object value) {
                obj.setBusinessLine((String)value);
            }
        }
        ,
        ProductLine {
            public Object get(DmsHtkpReturnEOImpl obj) {
                return obj.getProductLine();
            }

            public void put(DmsHtkpReturnEOImpl obj, Object value) {
                obj.setProductLine((String)value);
            }
        }
        ,
        ProjectType {
            public Object get(DmsHtkpReturnEOImpl obj) {
                return obj.getProjectType();
            }

            public void put(DmsHtkpReturnEOImpl obj, Object value) {
                obj.setProjectType((String)value);
            }
        }
        ,
        ContractBillingDetail {
            public Object get(DmsHtkpReturnEOImpl obj) {
                return obj.getContractBillingDetail();
            }

            public void put(DmsHtkpReturnEOImpl obj, Object value) {
                obj.setContractBillingDetail((String)value);
            }
        }
        ,
        Responsible {
            public Object get(DmsHtkpReturnEOImpl obj) {
                return obj.getResponsible();
            }

            public void put(DmsHtkpReturnEOImpl obj, Object value) {
                obj.setResponsible((String)value);
            }
        }
        ,
        CurJan {
            public Object get(DmsHtkpReturnEOImpl obj) {
                return obj.getCurJan();
            }

            public void put(DmsHtkpReturnEOImpl obj, Object value) {
                obj.setCurJan((Number)value);
            }
        }
        ,
        CurFeb {
            public Object get(DmsHtkpReturnEOImpl obj) {
                return obj.getCurFeb();
            }

            public void put(DmsHtkpReturnEOImpl obj, Object value) {
                obj.setCurFeb((Number)value);
            }
        }
        ,
        CurMar {
            public Object get(DmsHtkpReturnEOImpl obj) {
                return obj.getCurMar();
            }

            public void put(DmsHtkpReturnEOImpl obj, Object value) {
                obj.setCurMar((Number)value);
            }
        }
        ,
        CurApr {
            public Object get(DmsHtkpReturnEOImpl obj) {
                return obj.getCurApr();
            }

            public void put(DmsHtkpReturnEOImpl obj, Object value) {
                obj.setCurApr((Number)value);
            }
        }
        ,
        CurMay {
            public Object get(DmsHtkpReturnEOImpl obj) {
                return obj.getCurMay();
            }

            public void put(DmsHtkpReturnEOImpl obj, Object value) {
                obj.setCurMay((Number)value);
            }
        }
        ,
        CurJun {
            public Object get(DmsHtkpReturnEOImpl obj) {
                return obj.getCurJun();
            }

            public void put(DmsHtkpReturnEOImpl obj, Object value) {
                obj.setCurJun((Number)value);
            }
        }
        ,
        CurJul {
            public Object get(DmsHtkpReturnEOImpl obj) {
                return obj.getCurJul();
            }

            public void put(DmsHtkpReturnEOImpl obj, Object value) {
                obj.setCurJul((Number)value);
            }
        }
        ,
        CurAug {
            public Object get(DmsHtkpReturnEOImpl obj) {
                return obj.getCurAug();
            }

            public void put(DmsHtkpReturnEOImpl obj, Object value) {
                obj.setCurAug((Number)value);
            }
        }
        ,
        CurSep {
            public Object get(DmsHtkpReturnEOImpl obj) {
                return obj.getCurSep();
            }

            public void put(DmsHtkpReturnEOImpl obj, Object value) {
                obj.setCurSep((Number)value);
            }
        }
        ,
        CurOct {
            public Object get(DmsHtkpReturnEOImpl obj) {
                return obj.getCurOct();
            }

            public void put(DmsHtkpReturnEOImpl obj, Object value) {
                obj.setCurOct((Number)value);
            }
        }
        ,
        CurNov {
            public Object get(DmsHtkpReturnEOImpl obj) {
                return obj.getCurNov();
            }

            public void put(DmsHtkpReturnEOImpl obj, Object value) {
                obj.setCurNov((Number)value);
            }
        }
        ,
        CurDec {
            public Object get(DmsHtkpReturnEOImpl obj) {
                return obj.getCurDec();
            }

            public void put(DmsHtkpReturnEOImpl obj, Object value) {
                obj.setCurDec((Number)value);
            }
        }
        ,
        NextJan {
            public Object get(DmsHtkpReturnEOImpl obj) {
                return obj.getNextJan();
            }

            public void put(DmsHtkpReturnEOImpl obj, Object value) {
                obj.setNextJan((Number)value);
            }
        }
        ,
        NextFeb {
            public Object get(DmsHtkpReturnEOImpl obj) {
                return obj.getNextFeb();
            }

            public void put(DmsHtkpReturnEOImpl obj, Object value) {
                obj.setNextFeb((Number)value);
            }
        }
        ,
        NextMar {
            public Object get(DmsHtkpReturnEOImpl obj) {
                return obj.getNextMar();
            }

            public void put(DmsHtkpReturnEOImpl obj, Object value) {
                obj.setNextMar((Number)value);
            }
        }
        ,
        NextApr {
            public Object get(DmsHtkpReturnEOImpl obj) {
                return obj.getNextApr();
            }

            public void put(DmsHtkpReturnEOImpl obj, Object value) {
                obj.setNextApr((Number)value);
            }
        }
        ,
        NextMay {
            public Object get(DmsHtkpReturnEOImpl obj) {
                return obj.getNextMay();
            }

            public void put(DmsHtkpReturnEOImpl obj, Object value) {
                obj.setNextMay((Number)value);
            }
        }
        ,
        NextJun {
            public Object get(DmsHtkpReturnEOImpl obj) {
                return obj.getNextJun();
            }

            public void put(DmsHtkpReturnEOImpl obj, Object value) {
                obj.setNextJun((Number)value);
            }
        }
        ,
        NextOthers {
            public Object get(DmsHtkpReturnEOImpl obj) {
                return obj.getNextOthers();
            }

            public void put(DmsHtkpReturnEOImpl obj, Object value) {
                obj.setNextOthers((Number)value);
            }
        }
        ,
        ComRecordId {
            public Object get(DmsHtkpReturnEOImpl obj) {
                return obj.getComRecordId();
            }

            public void put(DmsHtkpReturnEOImpl obj, Object value) {
                obj.setComRecordId((String)value);
            }
        }
        ,
        Idx {
            public Object get(DmsHtkpReturnEOImpl obj) {
                return obj.getIdx();
            }

            public void put(DmsHtkpReturnEOImpl obj, Object value) {
                obj.setIdx((String)value);
            }
        }
        ,
        CreatedAt {
            public Object get(DmsHtkpReturnEOImpl obj) {
                return obj.getCreatedAt();
            }

            public void put(DmsHtkpReturnEOImpl obj, Object value) {
                obj.setCreatedAt((Date)value);
            }
        }
        ,
        UpdatedAt {
            public Object get(DmsHtkpReturnEOImpl obj) {
                return obj.getUpdatedAt();
            }

            public void put(DmsHtkpReturnEOImpl obj, Object value) {
                obj.setUpdatedAt((Date)value);
            }
        }
        ,
        CreatedBy {
            public Object get(DmsHtkpReturnEOImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(DmsHtkpReturnEOImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        UpdatedBy {
            public Object get(DmsHtkpReturnEOImpl obj) {
                return obj.getUpdatedBy();
            }

            public void put(DmsHtkpReturnEOImpl obj, Object value) {
                obj.setUpdatedBy((String)value);
            }
        }
        ,
        TaxRate {
            public Object get(DmsHtkpReturnEOImpl obj) {
                return obj.getTaxRate();
            }

            public void put(DmsHtkpReturnEOImpl obj, Object value) {
                obj.setTaxRate((Number)value);
            }
        }
        ,
        LastDec {
            public Object get(DmsHtkpReturnEOImpl obj) {
                return obj.getLastDec();
            }

            public void put(DmsHtkpReturnEOImpl obj, Object value) {
                obj.setLastDec((Number)value);
            }
        }
        ,
        LastNov {
            public Object get(DmsHtkpReturnEOImpl obj) {
                return obj.getLastNov();
            }

            public void put(DmsHtkpReturnEOImpl obj, Object value) {
                obj.setLastNov((Number)value);
            }
        }
        ,
        LastOct {
            public Object get(DmsHtkpReturnEOImpl obj) {
                return obj.getLastOct();
            }

            public void put(DmsHtkpReturnEOImpl obj, Object value) {
                obj.setLastOct((Number)value);
            }
        }
        ,
        OccurCost {
            public Object get(DmsHtkpReturnEOImpl obj) {
                return obj.getOccurCost();
            }

            public void put(DmsHtkpReturnEOImpl obj, Object value) {
                obj.setOccurCost((Number)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(DmsHtkpReturnEOImpl object);

        public abstract void put(DmsHtkpReturnEOImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ENTITY1 = AttributesEnum.Entity1.index();
    public static final int INDUSTRYLINE = AttributesEnum.IndustryLine.index();
    public static final int BUSINESSLINE = AttributesEnum.BusinessLine.index();
    public static final int PRODUCTLINE = AttributesEnum.ProductLine.index();
    public static final int PROJECTTYPE = AttributesEnum.ProjectType.index();
    public static final int CONTRACTBILLINGDETAIL = AttributesEnum.ContractBillingDetail.index();
    public static final int RESPONSIBLE = AttributesEnum.Responsible.index();
    public static final int CURJAN = AttributesEnum.CurJan.index();
    public static final int CURFEB = AttributesEnum.CurFeb.index();
    public static final int CURMAR = AttributesEnum.CurMar.index();
    public static final int CURAPR = AttributesEnum.CurApr.index();
    public static final int CURMAY = AttributesEnum.CurMay.index();
    public static final int CURJUN = AttributesEnum.CurJun.index();
    public static final int CURJUL = AttributesEnum.CurJul.index();
    public static final int CURAUG = AttributesEnum.CurAug.index();
    public static final int CURSEP = AttributesEnum.CurSep.index();
    public static final int CUROCT = AttributesEnum.CurOct.index();
    public static final int CURNOV = AttributesEnum.CurNov.index();
    public static final int CURDEC = AttributesEnum.CurDec.index();
    public static final int NEXTJAN = AttributesEnum.NextJan.index();
    public static final int NEXTFEB = AttributesEnum.NextFeb.index();
    public static final int NEXTMAR = AttributesEnum.NextMar.index();
    public static final int NEXTAPR = AttributesEnum.NextApr.index();
    public static final int NEXTMAY = AttributesEnum.NextMay.index();
    public static final int NEXTJUN = AttributesEnum.NextJun.index();
    public static final int NEXTOTHERS = AttributesEnum.NextOthers.index();
    public static final int COMRECORDID = AttributesEnum.ComRecordId.index();
    public static final int IDX = AttributesEnum.Idx.index();
    public static final int CREATEDAT = AttributesEnum.CreatedAt.index();
    public static final int UPDATEDAT = AttributesEnum.UpdatedAt.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int TAXRATE = AttributesEnum.TaxRate.index();
    public static final int LASTDEC = AttributesEnum.LastDec.index();
    public static final int LASTNOV = AttributesEnum.LastNov.index();
    public static final int LASTOCT = AttributesEnum.LastOct.index();
    public static final int OCCURCOST = AttributesEnum.OccurCost.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DmsHtkpReturnEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("team.epm.dms.model.DmsHtkpReturnEO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for Entity1, using the alias name Entity1.
     * @return the Entity1
     */
    public String getEntity1() {
        return (String)getAttributeInternal(ENTITY1);
    }

    /**
     * Sets <code>value</code> as the attribute value for Entity1.
     * @param value value to set the Entity1
     */
    public void setEntity1(String value) {
        setAttributeInternal(ENTITY1, value);
    }

    /**
     * Gets the attribute value for IndustryLine, using the alias name IndustryLine.
     * @return the IndustryLine
     */
    public String getIndustryLine() {
        return (String)getAttributeInternal(INDUSTRYLINE);
    }

    /**
     * Sets <code>value</code> as the attribute value for IndustryLine.
     * @param value value to set the IndustryLine
     */
    public void setIndustryLine(String value) {
        setAttributeInternal(INDUSTRYLINE, value);
    }

    /**
     * Gets the attribute value for BusinessLine, using the alias name BusinessLine.
     * @return the BusinessLine
     */
    public String getBusinessLine() {
        return (String)getAttributeInternal(BUSINESSLINE);
    }

    /**
     * Sets <code>value</code> as the attribute value for BusinessLine.
     * @param value value to set the BusinessLine
     */
    public void setBusinessLine(String value) {
        setAttributeInternal(BUSINESSLINE, value);
    }

    /**
     * Gets the attribute value for ProductLine, using the alias name ProductLine.
     * @return the ProductLine
     */
    public String getProductLine() {
        return (String)getAttributeInternal(PRODUCTLINE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProductLine.
     * @param value value to set the ProductLine
     */
    public void setProductLine(String value) {
        setAttributeInternal(PRODUCTLINE, value);
    }

    /**
     * Gets the attribute value for ProjectType, using the alias name ProjectType.
     * @return the ProjectType
     */
    public String getProjectType() {
        return (String)getAttributeInternal(PROJECTTYPE);
    }

    /**
     * Sets <code>value</code> as the attribute value for ProjectType.
     * @param value value to set the ProjectType
     */
    public void setProjectType(String value) {
        setAttributeInternal(PROJECTTYPE, value);
    }

    /**
     * Gets the attribute value for ContractBillingDetail, using the alias name ContractBillingDetail.
     * @return the ContractBillingDetail
     */
    public String getContractBillingDetail() {
        return (String)getAttributeInternal(CONTRACTBILLINGDETAIL);
    }

    /**
     * Sets <code>value</code> as the attribute value for ContractBillingDetail.
     * @param value value to set the ContractBillingDetail
     */
    public void setContractBillingDetail(String value) {
        setAttributeInternal(CONTRACTBILLINGDETAIL, value);
    }

    /**
     * Gets the attribute value for Responsible, using the alias name Responsible.
     * @return the Responsible
     */
    public String getResponsible() {
        return (String)getAttributeInternal(RESPONSIBLE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Responsible.
     * @param value value to set the Responsible
     */
    public void setResponsible(String value) {
        setAttributeInternal(RESPONSIBLE, value);
    }


    /**
     * Gets the attribute value for CurJan, using the alias name CurJan.
     * @return the CurJan
     */
    public Number getCurJan() {
        return (Number)getAttributeInternal(CURJAN);
    }

    /**
     * Sets <code>value</code> as the attribute value for CurJan.
     * @param value value to set the CurJan
     */
    public void setCurJan(Number value) {
        setAttributeInternal(CURJAN, value);
    }

    /**
     * Gets the attribute value for CurFeb, using the alias name CurFeb.
     * @return the CurFeb
     */
    public Number getCurFeb() {
        return (Number)getAttributeInternal(CURFEB);
    }

    /**
     * Sets <code>value</code> as the attribute value for CurFeb.
     * @param value value to set the CurFeb
     */
    public void setCurFeb(Number value) {
        setAttributeInternal(CURFEB, value);
    }

    /**
     * Gets the attribute value for CurMar, using the alias name CurMar.
     * @return the CurMar
     */
    public Number getCurMar() {
        return (Number)getAttributeInternal(CURMAR);
    }

    /**
     * Sets <code>value</code> as the attribute value for CurMar.
     * @param value value to set the CurMar
     */
    public void setCurMar(Number value) {
        setAttributeInternal(CURMAR, value);
    }

    /**
     * Gets the attribute value for CurApr, using the alias name CurApr.
     * @return the CurApr
     */
    public Number getCurApr() {
        return (Number)getAttributeInternal(CURAPR);
    }

    /**
     * Sets <code>value</code> as the attribute value for CurApr.
     * @param value value to set the CurApr
     */
    public void setCurApr(Number value) {
        setAttributeInternal(CURAPR, value);
    }

    /**
     * Gets the attribute value for CurMay, using the alias name CurMay.
     * @return the CurMay
     */
    public Number getCurMay() {
        return (Number)getAttributeInternal(CURMAY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CurMay.
     * @param value value to set the CurMay
     */
    public void setCurMay(Number value) {
        setAttributeInternal(CURMAY, value);
    }

    /**
     * Gets the attribute value for CurJun, using the alias name CurJun.
     * @return the CurJun
     */
    public Number getCurJun() {
        return (Number)getAttributeInternal(CURJUN);
    }

    /**
     * Sets <code>value</code> as the attribute value for CurJun.
     * @param value value to set the CurJun
     */
    public void setCurJun(Number value) {
        setAttributeInternal(CURJUN, value);
    }

    /**
     * Gets the attribute value for CurJul, using the alias name CurJul.
     * @return the CurJul
     */
    public Number getCurJul() {
        return (Number)getAttributeInternal(CURJUL);
    }

    /**
     * Sets <code>value</code> as the attribute value for CurJul.
     * @param value value to set the CurJul
     */
    public void setCurJul(Number value) {
        setAttributeInternal(CURJUL, value);
    }

    /**
     * Gets the attribute value for CurAug, using the alias name CurAug.
     * @return the CurAug
     */
    public Number getCurAug() {
        return (Number)getAttributeInternal(CURAUG);
    }

    /**
     * Sets <code>value</code> as the attribute value for CurAug.
     * @param value value to set the CurAug
     */
    public void setCurAug(Number value) {
        setAttributeInternal(CURAUG, value);
    }

    /**
     * Gets the attribute value for CurSep, using the alias name CurSep.
     * @return the CurSep
     */
    public Number getCurSep() {
        return (Number)getAttributeInternal(CURSEP);
    }

    /**
     * Sets <code>value</code> as the attribute value for CurSep.
     * @param value value to set the CurSep
     */
    public void setCurSep(Number value) {
        setAttributeInternal(CURSEP, value);
    }

    /**
     * Gets the attribute value for CurOct, using the alias name CurOct.
     * @return the CurOct
     */
    public Number getCurOct() {
        return (Number)getAttributeInternal(CUROCT);
    }

    /**
     * Sets <code>value</code> as the attribute value for CurOct.
     * @param value value to set the CurOct
     */
    public void setCurOct(Number value) {
        setAttributeInternal(CUROCT, value);
    }

    /**
     * Gets the attribute value for CurNov, using the alias name CurNov.
     * @return the CurNov
     */
    public Number getCurNov() {
        return (Number)getAttributeInternal(CURNOV);
    }

    /**
     * Sets <code>value</code> as the attribute value for CurNov.
     * @param value value to set the CurNov
     */
    public void setCurNov(Number value) {
        setAttributeInternal(CURNOV, value);
    }

    /**
     * Gets the attribute value for CurDec, using the alias name CurDec.
     * @return the CurDec
     */
    public Number getCurDec() {
        return (Number)getAttributeInternal(CURDEC);
    }

    /**
     * Sets <code>value</code> as the attribute value for CurDec.
     * @param value value to set the CurDec
     */
    public void setCurDec(Number value) {
        setAttributeInternal(CURDEC, value);
    }

    /**
     * Gets the attribute value for NextJan, using the alias name NextJan.
     * @return the NextJan
     */
    public Number getNextJan() {
        return (Number)getAttributeInternal(NEXTJAN);
    }

    /**
     * Sets <code>value</code> as the attribute value for NextJan.
     * @param value value to set the NextJan
     */
    public void setNextJan(Number value) {
        setAttributeInternal(NEXTJAN, value);
    }

    /**
     * Gets the attribute value for NextFeb, using the alias name NextFeb.
     * @return the NextFeb
     */
    public Number getNextFeb() {
        return (Number)getAttributeInternal(NEXTFEB);
    }

    /**
     * Sets <code>value</code> as the attribute value for NextFeb.
     * @param value value to set the NextFeb
     */
    public void setNextFeb(Number value) {
        setAttributeInternal(NEXTFEB, value);
    }

    /**
     * Gets the attribute value for NextMar, using the alias name NextMar.
     * @return the NextMar
     */
    public Number getNextMar() {
        return (Number)getAttributeInternal(NEXTMAR);
    }

    /**
     * Sets <code>value</code> as the attribute value for NextMar.
     * @param value value to set the NextMar
     */
    public void setNextMar(Number value) {
        setAttributeInternal(NEXTMAR, value);
    }

    /**
     * Gets the attribute value for NextApr, using the alias name NextApr.
     * @return the NextApr
     */
    public Number getNextApr() {
        return (Number)getAttributeInternal(NEXTAPR);
    }

    /**
     * Sets <code>value</code> as the attribute value for NextApr.
     * @param value value to set the NextApr
     */
    public void setNextApr(Number value) {
        setAttributeInternal(NEXTAPR, value);
    }

    /**
     * Gets the attribute value for NextMay, using the alias name NextMay.
     * @return the NextMay
     */
    public Number getNextMay() {
        return (Number)getAttributeInternal(NEXTMAY);
    }

    /**
     * Sets <code>value</code> as the attribute value for NextMay.
     * @param value value to set the NextMay
     */
    public void setNextMay(Number value) {
        setAttributeInternal(NEXTMAY, value);
    }

    /**
     * Gets the attribute value for NextJun, using the alias name NextJun.
     * @return the NextJun
     */
    public Number getNextJun() {
        return (Number)getAttributeInternal(NEXTJUN);
    }

    /**
     * Sets <code>value</code> as the attribute value for NextJun.
     * @param value value to set the NextJun
     */
    public void setNextJun(Number value) {
        setAttributeInternal(NEXTJUN, value);
    }

    /**
     * Gets the attribute value for NextOthers, using the alias name NextOthers.
     * @return the NextOthers
     */
    public Number getNextOthers() {
        return (Number)getAttributeInternal(NEXTOTHERS);
    }

    /**
     * Sets <code>value</code> as the attribute value for NextOthers.
     * @param value value to set the NextOthers
     */
    public void setNextOthers(Number value) {
        setAttributeInternal(NEXTOTHERS, value);
    }

    /**
     * Gets the attribute value for ComRecordId, using the alias name ComRecordId.
     * @return the ComRecordId
     */
    public String getComRecordId() {
        return (String)getAttributeInternal(COMRECORDID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ComRecordId.
     * @param value value to set the ComRecordId
     */
    public void setComRecordId(String value) {
        setAttributeInternal(COMRECORDID, value);
    }

    /**
     * Gets the attribute value for Idx, using the alias name Idx.
     * @return the Idx
     */
    public String getIdx() {
        return (String)getAttributeInternal(IDX);
    }

    /**
     * Sets <code>value</code> as the attribute value for Idx.
     * @param value value to set the Idx
     */
    public void setIdx(String value) {
        setAttributeInternal(IDX, value);
    }

    /**
     * Gets the attribute value for CreatedAt, using the alias name CreatedAt.
     * @return the CreatedAt
     */
    public Date getCreatedAt() {
        return (Date)getAttributeInternal(CREATEDAT);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedAt.
     * @param value value to set the CreatedAt
     */
    public void setCreatedAt(Date value) {
        setAttributeInternal(CREATEDAT, value);
    }

    /**
     * Gets the attribute value for UpdatedAt, using the alias name UpdatedAt.
     * @return the UpdatedAt
     */
    public Date getUpdatedAt() {
        return (Date)getAttributeInternal(UPDATEDAT);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedAt.
     * @param value value to set the UpdatedAt
     */
    public void setUpdatedAt(Date value) {
        setAttributeInternal(UPDATEDAT, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the UpdatedBy
     */
    public String getUpdatedBy() {
        return (String)getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(String value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for TaxRate, using the alias name TaxRate.
     * @return the TaxRate
     */
    public Number getTaxRate() {
        return (Number)getAttributeInternal(TAXRATE);
    }

    /**
     * Sets <code>value</code> as the attribute value for TaxRate.
     * @param value value to set the TaxRate
     */
    public void setTaxRate(Number value) {
        setAttributeInternal(TAXRATE, value);
    }

    /**
     * Gets the attribute value for LastDec, using the alias name LastDec.
     * @return the LastDec
     */
    public Number getLastDec() {
        return (Number)getAttributeInternal(LASTDEC);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastDec.
     * @param value value to set the LastDec
     */
    public void setLastDec(Number value) {
        setAttributeInternal(LASTDEC, value);
    }

    /**
     * Gets the attribute value for LastNov, using the alias name LastNov.
     * @return the LastNov
     */
    public Number getLastNov() {
        return (Number)getAttributeInternal(LASTNOV);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastNov.
     * @param value value to set the LastNov
     */
    public void setLastNov(Number value) {
        setAttributeInternal(LASTNOV, value);
    }

    /**
     * Gets the attribute value for LastOct, using the alias name LastOct.
     * @return the LastOct
     */
    public Number getLastOct() {
        return (Number)getAttributeInternal(LASTOCT);
    }

    /**
     * Sets <code>value</code> as the attribute value for LastOct.
     * @param value value to set the LastOct
     */
    public void setLastOct(Number value) {
        setAttributeInternal(LASTOCT, value);
    }

    /**
     * Gets the attribute value for OccurCost, using the alias name OccurCost.
     * @return the OccurCost
     */
    public Number getOccurCost() {
        return (Number)getAttributeInternal(OCCURCOST);
    }

    /**
     * Sets <code>value</code> as the attribute value for OccurCost.
     * @param value value to set the OccurCost
     */
    public void setOccurCost(Number value) {
        setAttributeInternal(OCCURCOST, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @param idx key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String idx) {
        return new Key(new Object[]{idx});
    }


}
