package team.epm.dms.model;

import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Aug 04 23:38:33 CST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DmsWorkflowStepsEOImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        Id,
        Locale,
        StepNo,
        StepTask,
        CreatedAt,
        UpdatedAt,
        CreatedBy,
        UpdatedBy,
        WfId,
        PreStep,
        ApproveObject,
        EtlObject,
        LabelObject,
        AfterPro;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int ID = AttributesEnum.Id.index();
    public static final int LOCALE = AttributesEnum.Locale.index();
    public static final int STEPNO = AttributesEnum.StepNo.index();
    public static final int STEPTASK = AttributesEnum.StepTask.index();
    public static final int CREATEDAT = AttributesEnum.CreatedAt.index();
    public static final int UPDATEDAT = AttributesEnum.UpdatedAt.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int WFID = AttributesEnum.WfId.index();
    public static final int PRESTEP = AttributesEnum.PreStep.index();
    public static final int APPROVEOBJECT = AttributesEnum.ApproveObject.index();
    public static final int ETLOBJECT = AttributesEnum.EtlObject.index();
    public static final int LABELOBJECT = AttributesEnum.LabelObject.index();
    public static final int AFTERPRO = AttributesEnum.AfterPro.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DmsWorkflowStepsEOImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("team.epm.dms.model.DmsWorkflowStepsEO");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for Id, using the alias name Id.
     * @return the Id
     */
    public String getId() {
        return (String)getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Id.
     * @param value value to set the Id
     */
    public void setId(String value) {
        setAttributeInternal(ID, value);
    }

    /**
     * Gets the attribute value for Locale, using the alias name Locale.
     * @return the Locale
     */
    public String getLocale() {
        return (String)getAttributeInternal(LOCALE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Locale.
     * @param value value to set the Locale
     */
    public void setLocale(String value) {
        setAttributeInternal(LOCALE, value);
    }

    /**
     * Gets the attribute value for StepNo, using the alias name StepNo.
     * @return the StepNo
     */
    public Number getStepNo() {
        return (Number)getAttributeInternal(STEPNO);
    }

    /**
     * Sets <code>value</code> as the attribute value for StepNo.
     * @param value value to set the StepNo
     */
    public void setStepNo(Number value) {
        setAttributeInternal(STEPNO, value);
    }

    /**
     * Gets the attribute value for StepTask, using the alias name StepTask.
     * @return the StepTask
     */
    public String getStepTask() {
        return (String)getAttributeInternal(STEPTASK);
    }

    /**
     * Sets <code>value</code> as the attribute value for StepTask.
     * @param value value to set the StepTask
     */
    public void setStepTask(String value) {
        setAttributeInternal(STEPTASK, value);
    }

    /**
     * Gets the attribute value for CreatedAt, using the alias name CreatedAt.
     * @return the CreatedAt
     */
    public Date getCreatedAt() {
        return (Date)getAttributeInternal(CREATEDAT);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedAt.
     * @param value value to set the CreatedAt
     */
    public void setCreatedAt(Date value) {
        setAttributeInternal(CREATEDAT, value);
    }

    /**
     * Gets the attribute value for UpdatedAt, using the alias name UpdatedAt.
     * @return the UpdatedAt
     */
    public Date getUpdatedAt() {
        return (Date)getAttributeInternal(UPDATEDAT);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedAt.
     * @param value value to set the UpdatedAt
     */
    public void setUpdatedAt(Date value) {
        setAttributeInternal(UPDATEDAT, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the UpdatedBy
     */
    public String getUpdatedBy() {
        return (String)getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(String value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for WfId, using the alias name WfId.
     * @return the WfId
     */
    public String getWfId() {
        return (String)getAttributeInternal(WFID);
    }

    /**
     * Sets <code>value</code> as the attribute value for WfId.
     * @param value value to set the WfId
     */
    public void setWfId(String value) {
        setAttributeInternal(WFID, value);
    }

    /**
     * Gets the attribute value for PreStep, using the alias name PreStep.
     * @return the PreStep
     */
    public String getPreStep() {
        return (String)getAttributeInternal(PRESTEP);
    }

    /**
     * Sets <code>value</code> as the attribute value for PreStep.
     * @param value value to set the PreStep
     */
    public void setPreStep(String value) {
        setAttributeInternal(PRESTEP, value);
    }

    /**
     * Gets the attribute value for ApproveObject, using the alias name ApproveObject.
     * @return the ApproveObject
     */
    public String getApproveObject() {
        return (String)getAttributeInternal(APPROVEOBJECT);
    }

    /**
     * Sets <code>value</code> as the attribute value for ApproveObject.
     * @param value value to set the ApproveObject
     */
    public void setApproveObject(String value) {
        setAttributeInternal(APPROVEOBJECT, value);
    }

    /**
     * Gets the attribute value for EtlObject, using the alias name EtlObject.
     * @return the EtlObject
     */
    public String getEtlObject() {
        return (String)getAttributeInternal(ETLOBJECT);
    }

    /**
     * Sets <code>value</code> as the attribute value for EtlObject.
     * @param value value to set the EtlObject
     */
    public void setEtlObject(String value) {
        setAttributeInternal(ETLOBJECT, value);
    }

    /**
     * Gets the attribute value for LabelObject, using the alias name LabelObject.
     * @return the LabelObject
     */
    public String getLabelObject() {
        return (String)getAttributeInternal(LABELOBJECT);
    }

    /**
     * Sets <code>value</code> as the attribute value for LabelObject.
     * @param value value to set the LabelObject
     */
    public void setLabelObject(String value) {
        setAttributeInternal(LABELOBJECT, value);
    }

    /**
     * Gets the attribute value for AfterPro, using the alias name AfterPro.
     * @return the AfterPro
     */
    public String getAfterPro() {
        return (String)getAttributeInternal(AFTERPRO);
    }

    /**
     * Sets <code>value</code> as the attribute value for AfterPro.
     * @param value value to set the AfterPro
     */
    public void setAfterPro(String value) {
        setAttributeInternal(AFTERPRO, value);
    }

    /**
     * @param id key constituent
     * @param locale key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String id, String locale) {
        return new Key(new Object[]{id, locale});
    }


}
