package team.epm.dms.view;

import java.sql.PreparedStatement;
import java.sql.SQLException;

import oracle.adf.share.logging.ADFLogger;

import oracle.jbo.server.DBTransaction;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Nov 07 10:07:55 CST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DmsGroupRoleViewImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    private static ADFLogger logger=ADFLogger.createADFLogger(DmsGroupRoleViewImpl.class);
    public DmsGroupRoleViewImpl() {
    }
    
    public void deleteGroupRoleByGroupIdAndRoleId(String RoleId,String GroupId){
        String sql="delete from dms_group_role t where t.group_id=? and t.role_id=?";
        PreparedStatement stat=this.getDBTransaction().createPreparedStatement(sql, DBTransaction.DEFAULT);
        try {
            stat.setString(1, GroupId);
            stat.setString(2, RoleId);
            stat.execute();
        } catch (SQLException e) {
            logger.severe(e);
        }
    }
}
