package team.epm.dms.view;

import oracle.jbo.RowSet;
import oracle.jbo.ViewCriteria;
import oracle.jbo.ViewCriteriaRow;
import oracle.jbo.server.ViewObjectImpl;

import team.epm.dms.view.common.DmsRoleView;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 06 19:23:45 CST 2014
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DmsRoleViewImpl extends ViewObjectImpl implements DmsRoleView {
    /**
     * This is the default constructor (do not remove).
     */
    public DmsRoleViewImpl() {
    }

    /**
     * Returns the bind variable value for locale.
     * @return bind variable value for locale
     */
    public String getlocale() {
        return (String)getNamedWhereClauseParam("locale");
    }

    /**
     * Sets <code>value</code> for bind variable locale.
     * @param value value to bind as locale
     */
    public void setlocale(String value) {
        setNamedWhereClauseParam("locale", value);
    }
    
    public RowSet fetchEnabledRole(){
        ViewCriteria vc= this.createViewCriteria();
        ViewCriteriaRow vcRow = vc.createViewCriteriaRow();
        vcRow.setAttribute("EnableFlag", "Y");
        vc.addElement(vcRow);
        this.applyViewCriteria(vc);
        this.executeQuery();
        this.createViewCriteria();
        return this.getRowSet();
    }
}
