package team.epm.module;

import java.util.Map;

import oracle.adf.share.ADFContext;

import oracle.jbo.Session;
import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Jan 23 20:04:50 CST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class Odi11gModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public Odi11gModuleImpl() {
    }
    @Override
    protected void prepareSession(Session session) {
        super.prepareSession(session);
        Map sessionScope = ADFContext.getCurrent().getSessionScope();
        Object userId = sessionScope.get("userId");
        if (userId != null) {
            this.getSession().getUserData().put("userId", userId);
        }
    }
    /**
     * Container's getter for Odi11AgentView.
     * @return Odi11AgentView
     */
    public ViewObjectImpl getOdi11AgentView() {
        return (ViewObjectImpl)findViewObject("Odi11AgentView");
    }

    /**
     * Container's getter for Odi11ParameterView.
     * @return Odi11ParameterView
     */
    public ViewObjectImpl getOdi11ParameterView() {
        return (ViewObjectImpl)findViewObject("Odi11ParameterView");
    }

    /**
     * Container's getter for Odi11SceneCatView.
     * @return Odi11SceneCatView
     */
    public ViewObjectImpl getOdi11SceneCatView() {
        return (ViewObjectImpl)findViewObject("Odi11SceneCatView");
    }

    /**
     * Container's getter for Odi11SceneExecView.
     * @return Odi11SceneExecView
     */
    public ViewObjectImpl getOdi11SceneExecView() {
        return (ViewObjectImpl)findViewObject("Odi11SceneExecView");
    }

    /**
     * Container's getter for Odi11SceneParamView.
     * @return Odi11SceneParamView
     */
    public ViewObjectImpl getOdi11SceneParamView() {
        return (ViewObjectImpl)findViewObject("Odi11SceneParamView");
    }

    /**
     * Container's getter for Odi11SceneView.
     * @return Odi11SceneView
     */
    public ViewObjectImpl getOdi11SceneView() {
        return (ViewObjectImpl)findViewObject("Odi11SceneView");
    }

    /**
     * Container's getter for Odi11WorkrepView.
     * @return Odi11WorkrepView
     */
    public ViewObjectImpl getOdi11WorkrepView() {
        return (ViewObjectImpl)findViewObject("Odi11WorkrepView");
    }
}
