package team.epm.dcm.view.client;

import oracle.jbo.client.remote.RowImpl;
import oracle.jbo.domain.Date;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Apr 19 17:07:15 CST 2016
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DcmTemplateCombinationVORowClient extends RowImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public DcmTemplateCombinationVORowClient() {
    }

    public String getComRecordId() {
        return (String)getAttribute("ComRecordId");
    }

    public void setComRecordId(String value) {
        setAttribute("ComRecordId", value);
    }

    public Date getCreatedAt() {
        return (Date)getAttribute("CreatedAt");
    }

    public void setCreatedAt(Date value) {
        setAttribute("CreatedAt", value);
    }

    public String getCreatedBy() {
        return (String)getAttribute("CreatedBy");
    }

    public void setCreatedBy(String value) {
        setAttribute("CreatedBy", value);
    }

    public String getId() {
        return (String)getAttribute("Id");
    }

    public void setId(String value) {
        setAttribute("Id", value);
    }

    public String getStatus() {
        return (String)getAttribute("Status");
    }

    public void setStatus(String value) {
        setAttribute("Status", value);
    }

    public String getTemplateId() {
        return (String)getAttribute("TemplateId");
    }

    public void setTemplateId(String value) {
        setAttribute("TemplateId", value);
    }

    public Date getUpdatedAt() {
        return (Date)getAttribute("UpdatedAt");
    }

    public void setUpdatedAt(Date value) {
        setAttribute("UpdatedAt", value);
    }

    public String getUpdatedBy() {
        return (String)getAttribute("UpdatedBy");
    }

    public void setUpdatedBy(String value) {
        setAttribute("UpdatedBy", value);
    }
}
