package team.epm.dcm.model;

import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;
import oracle.jbo.server.TransactionEvent;

import org.apache.commons.lang.ObjectUtils;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Mon Jan 26 10:10:28 CST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DcmComVsImpl extends EntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        CombinationId {
            public Object get(DcmComVsImpl obj) {
                return obj.getCombinationId();
            }

            public void put(DcmComVsImpl obj, Object value) {
                obj.setCombinationId((String)value);
            }
        }
        ,
        ValueSetId {
            public Object get(DcmComVsImpl obj) {
                return obj.getValueSetId();
            }

            public void put(DcmComVsImpl obj, Object value) {
                obj.setValueSetId((String)value);
            }
        }
        ,
        Seq {
            public Object get(DcmComVsImpl obj) {
                return obj.getSeq();
            }

            public void put(DcmComVsImpl obj, Object value) {
                obj.setSeq((Number)value);
            }
        }
        ,
        IsAuthority {
            public Object get(DcmComVsImpl obj) {
                return obj.getIsAuthority();
            }

            public void put(DcmComVsImpl obj, Object value) {
                obj.setIsAuthority((String)value);
            }
        }
        ,
        CreatedAt {
            public Object get(DcmComVsImpl obj) {
                return obj.getCreatedAt();
            }

            public void put(DcmComVsImpl obj, Object value) {
                obj.setCreatedAt((Date)value);
            }
        }
        ,
        UpdatedAt {
            public Object get(DcmComVsImpl obj) {
                return obj.getUpdatedAt();
            }

            public void put(DcmComVsImpl obj, Object value) {
                obj.setUpdatedAt((Date)value);
            }
        }
        ,
        UpdatedBy {
            public Object get(DcmComVsImpl obj) {
                return obj.getUpdatedBy();
            }

            public void put(DcmComVsImpl obj, Object value) {
                obj.setUpdatedBy((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(DcmComVsImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(DcmComVsImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        IsApproval {
            public Object get(DcmComVsImpl obj) {
                return obj.getIsApproval();
            }

            public void put(DcmComVsImpl obj, Object value) {
                obj.setIsApproval((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(DcmComVsImpl object);

        public abstract void put(DcmComVsImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }

    public static final int COMBINATIONID = AttributesEnum.CombinationId.index();
    public static final int VALUESETID = AttributesEnum.ValueSetId.index();
    public static final int SEQ = AttributesEnum.Seq.index();
    public static final int ISAUTHORITY = AttributesEnum.IsAuthority.index();
    public static final int CREATEDAT = AttributesEnum.CreatedAt.index();
    public static final int UPDATEDAT = AttributesEnum.UpdatedAt.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int ISAPPROVAL = AttributesEnum.IsApproval.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DcmComVsImpl() {
    }

    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("team.epm.dcm.model.DcmComVs");
        }
        return mDefinitionObject;
    }

    @Override
    protected void prepareForDML(int operation,
                                 TransactionEvent transactionEvent) {
        super.prepareForDML(operation, transactionEvent);
        if (operation == DML_UPDATE) {
            this.setUpdatedAt(new Date(new java.sql.Timestamp(System.currentTimeMillis())));
            this.setUpdatedBy(ObjectUtils.toString(this.getDBTransaction().getSession().getUserData().get("userId")));
        }
    }
    /**
     * Gets the attribute value for CombinationId, using the alias name CombinationId.
     * @return the CombinationId
     */
    public String getCombinationId() {
        return (String)getAttributeInternal(COMBINATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for CombinationId.
     * @param value value to set the CombinationId
     */
    public void setCombinationId(String value) {
        setAttributeInternal(COMBINATIONID, value);
    }

    /**
     * Gets the attribute value for ValueSetId, using the alias name ValueSetId.
     * @return the ValueSetId
     */
    public String getValueSetId() {
        return (String)getAttributeInternal(VALUESETID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ValueSetId.
     * @param value value to set the ValueSetId
     */
    public void setValueSetId(String value) {
        setAttributeInternal(VALUESETID, value);
    }

    /**
     * Gets the attribute value for Seq, using the alias name Seq.
     * @return the Seq
     */
    public Number getSeq() {
        return (Number)getAttributeInternal(SEQ);
    }

    /**
     * Sets <code>value</code> as the attribute value for Seq.
     * @param value value to set the Seq
     */
    public void setSeq(Number value) {
        setAttributeInternal(SEQ, value);
    }

    /**
     * Gets the attribute value for IsAuthority, using the alias name IsAuthority.
     * @return the IsAuthority
     */
    public String getIsAuthority() {
        return (String)getAttributeInternal(ISAUTHORITY);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsAuthority.
     * @param value value to set the IsAuthority
     */
    public void setIsAuthority(String value) {
        setAttributeInternal(ISAUTHORITY, value);
    }

    /**
     * Gets the attribute value for CreatedAt, using the alias name CreatedAt.
     * @return the CreatedAt
     */
    public Date getCreatedAt() {
        return (Date)getAttributeInternal(CREATEDAT);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedAt.
     * @param value value to set the CreatedAt
     */
    public void setCreatedAt(Date value) {
        setAttributeInternal(CREATEDAT, value);
    }

    /**
     * Gets the attribute value for UpdatedAt, using the alias name UpdatedAt.
     * @return the UpdatedAt
     */
    public Date getUpdatedAt() {
        return (Date)getAttributeInternal(UPDATEDAT);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedAt.
     * @param value value to set the UpdatedAt
     */
    public void setUpdatedAt(Date value) {
        setAttributeInternal(UPDATEDAT, value);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the UpdatedBy
     */
    public String getUpdatedBy() {
        return (String)getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(String value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for IsApproval, using the alias name IsApproval.
     * @return the IsApproval
     */
    public String getIsApproval() {
        return (String)getAttributeInternal(ISAPPROVAL);
    }

    /**
     * Sets <code>value</code> as the attribute value for IsApproval.
     * @param value value to set the IsApproval
     */
    public void setIsApproval(String value) {
        setAttributeInternal(ISAPPROVAL, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @param combinationId key constituent
     * @param valueSetId key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String combinationId,
                                       String valueSetId) {
        return new Key(new Object[]{combinationId, valueSetId});
    }


}
