package team.epm.dcm.model;

import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.EntityImpl;

import team.epm.dms.common.DmsEntityImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Wed Feb 04 18:02:14 CST 2015
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class DcmErrorImpl extends DmsEntityImpl {
    private static EntityDefImpl mDefinitionObject;

    /**
     * AttributesEnum: generated enum for identifying attributes and accessors. DO NOT MODIFY.
     */
    public enum AttributesEnum {
        SheetName {
            public Object get(DcmErrorImpl obj) {
                return obj.getSheetName();
            }

            public void put(DcmErrorImpl obj, Object value) {
                obj.setSheetName((String)value);
            }
        }
        ,
        RowNum {
            public Object get(DcmErrorImpl obj) {
                return obj.getRowNum();
            }

            public void put(DcmErrorImpl obj, Object value) {
                obj.setRowNum((Number)value);
            }
        }
        ,
        Msg {
            public Object get(DcmErrorImpl obj) {
                return obj.getMsg();
            }

            public void put(DcmErrorImpl obj, Object value) {
                obj.setMsg((String)value);
            }
        }
        ,
        Level {
            public Object get(DcmErrorImpl obj) {
                return obj.getLevel();
            }

            public void put(DcmErrorImpl obj, Object value) {
                obj.setLevel((String)value);
            }
        }
        ,
        Locale {
            public Object get(DcmErrorImpl obj) {
                return obj.getLocale();
            }

            public void put(DcmErrorImpl obj, Object value) {
                obj.setLocale((String)value);
            }
        }
        ,
        ValidationId {
            public Object get(DcmErrorImpl obj) {
                return obj.getValidationId();
            }

            public void put(DcmErrorImpl obj, Object value) {
                obj.setValidationId((String)value);
            }
        }
        ,
        CreatedAt {
            public Object get(DcmErrorImpl obj) {
                return obj.getCreatedAt();
            }

            public void put(DcmErrorImpl obj, Object value) {
                obj.setCreatedAt((Date)value);
            }
        }
        ,
        UpdatedAt {
            public Object get(DcmErrorImpl obj) {
                return obj.getUpdatedAt();
            }

            public void put(DcmErrorImpl obj, Object value) {
                obj.setUpdatedAt((Date)value);
            }
        }
        ,
        UpdatedBy {
            public Object get(DcmErrorImpl obj) {
                return obj.getUpdatedBy();
            }

            public void put(DcmErrorImpl obj, Object value) {
                obj.setUpdatedBy((String)value);
            }
        }
        ,
        CreatedBy {
            public Object get(DcmErrorImpl obj) {
                return obj.getCreatedBy();
            }

            public void put(DcmErrorImpl obj, Object value) {
                obj.setCreatedBy((String)value);
            }
        }
        ,
        TemplateId {
            public Object get(DcmErrorImpl obj) {
                return obj.getTemplateId();
            }

            public void put(DcmErrorImpl obj, Object value) {
                obj.setTemplateId((String)value);
            }
        }
        ,
        ComRecordId {
            public Object get(DcmErrorImpl obj) {
                return obj.getComRecordId();
            }

            public void put(DcmErrorImpl obj, Object value) {
                obj.setComRecordId((String)value);
            }
        }
        ,
        Id {
            public Object get(DcmErrorImpl obj) {
                return obj.getId();
            }

            public void put(DcmErrorImpl obj, Object value) {
                obj.setId((String)value);
            }
        }
        ;
        private static AttributesEnum[] vals = null;
        private static final int firstIndex = 0;

        public abstract Object get(DcmErrorImpl object);

        public abstract void put(DcmErrorImpl object, Object value);

        public int index() {
            return AttributesEnum.firstIndex() + ordinal();
        }

        public static final int firstIndex() {
            return firstIndex;
        }

        public static int count() {
            return AttributesEnum.firstIndex() + AttributesEnum.staticValues().length;
        }

        public static final AttributesEnum[] staticValues() {
            if (vals == null) {
                vals = AttributesEnum.values();
            }
            return vals;
        }
    }


    public static final int SHEETNAME = AttributesEnum.SheetName.index();
    public static final int ROWNUM = AttributesEnum.RowNum.index();
    public static final int MSG = AttributesEnum.Msg.index();
    public static final int LEVEL = AttributesEnum.Level.index();
    public static final int LOCALE = AttributesEnum.Locale.index();
    public static final int VALIDATIONID = AttributesEnum.ValidationId.index();
    public static final int CREATEDAT = AttributesEnum.CreatedAt.index();
    public static final int UPDATEDAT = AttributesEnum.UpdatedAt.index();
    public static final int UPDATEDBY = AttributesEnum.UpdatedBy.index();
    public static final int CREATEDBY = AttributesEnum.CreatedBy.index();
    public static final int TEMPLATEID = AttributesEnum.TemplateId.index();
    public static final int COMRECORDID = AttributesEnum.ComRecordId.index();
    public static final int ID = AttributesEnum.Id.index();

    /**
     * This is the default constructor (do not remove).
     */
    public DcmErrorImpl() {
    }


    /**
     * @return the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = EntityDefImpl.findDefObject("team.epm.dcm.model.DcmError");
        }
        return mDefinitionObject;
    }

    /**
     * Gets the attribute value for SheetName, using the alias name SheetName.
     * @return the SheetName
     */
    public String getSheetName() {
        return (String)getAttributeInternal(SHEETNAME);
    }

    /**
     * Sets <code>value</code> as the attribute value for SheetName.
     * @param value value to set the SheetName
     */
    public void setSheetName(String value) {
        setAttributeInternal(SHEETNAME, value);
    }

    /**
     * Gets the attribute value for RowNum, using the alias name RowNum.
     * @return the RowNum
     */
    public Number getRowNum() {
        return (Number)getAttributeInternal(ROWNUM);
    }

    /**
     * Sets <code>value</code> as the attribute value for RowNum.
     * @param value value to set the RowNum
     */
    public void setRowNum(Number value) {
        setAttributeInternal(ROWNUM, value);
    }

    /**
     * Gets the attribute value for Msg, using the alias name Msg.
     * @return the Msg
     */
    public String getMsg() {
        return (String)getAttributeInternal(MSG);
    }

    /**
     * Sets <code>value</code> as the attribute value for Msg.
     * @param value value to set the Msg
     */
    public void setMsg(String value) {
        setAttributeInternal(MSG, value);
    }

    /**
     * Gets the attribute value for Level, using the alias name Level.
     * @return the Level
     */
    public String getLevel() {
        return (String)getAttributeInternal(LEVEL);
    }

    /**
     * Sets <code>value</code> as the attribute value for Level.
     * @param value value to set the Level
     */
    public void setLevel(String value) {
        setAttributeInternal(LEVEL, value);
    }

    /**
     * Gets the attribute value for Locale, using the alias name Locale.
     * @return the Locale
     */
    public String getLocale() {
        return (String)getAttributeInternal(LOCALE);
    }

    /**
     * Sets <code>value</code> as the attribute value for Locale.
     * @param value value to set the Locale
     */
    public void setLocale(String value) {
        setAttributeInternal(LOCALE, value);
    }

    /**
     * Gets the attribute value for ValidationId, using the alias name ValidationId.
     * @return the ValidationId
     */
    public String getValidationId() {
        return (String)getAttributeInternal(VALIDATIONID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ValidationId.
     * @param value value to set the ValidationId
     */
    public void setValidationId(String value) {
        setAttributeInternal(VALIDATIONID, value);
    }

    /**
     * Gets the attribute value for CreatedAt, using the alias name CreatedAt.
     * @return the CreatedAt
     */
    public Date getCreatedAt() {
        return (Date)getAttributeInternal(CREATEDAT);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedAt.
     * @param value value to set the CreatedAt
     */
    public void setCreatedAt(Date value) {
        setAttributeInternal(CREATEDAT, value);
    }

    /**
     * Gets the attribute value for UpdatedAt, using the alias name UpdatedAt.
     * @return the UpdatedAt
     */
    public Date getUpdatedAt() {
        return (Date)getAttributeInternal(UPDATEDAT);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedAt.
     * @param value value to set the UpdatedAt
     */
    public void setUpdatedAt(Date value) {
        setAttributeInternal(UPDATEDAT, value);
    }

    /**
     * Gets the attribute value for UpdatedBy, using the alias name UpdatedBy.
     * @return the UpdatedBy
     */
    public String getUpdatedBy() {
        return (String)getAttributeInternal(UPDATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for UpdatedBy.
     * @param value value to set the UpdatedBy
     */
    public void setUpdatedBy(String value) {
        setAttributeInternal(UPDATEDBY, value);
    }

    /**
     * Gets the attribute value for CreatedBy, using the alias name CreatedBy.
     * @return the CreatedBy
     */
    public String getCreatedBy() {
        return (String)getAttributeInternal(CREATEDBY);
    }

    /**
     * Sets <code>value</code> as the attribute value for CreatedBy.
     * @param value value to set the CreatedBy
     */
    public void setCreatedBy(String value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**
     * Gets the attribute value for TemplateId, using the alias name TemplateId.
     * @return the TemplateId
     */
    public String getTemplateId() {
        return (String)getAttributeInternal(TEMPLATEID);
    }

    /**
     * Sets <code>value</code> as the attribute value for TemplateId.
     * @param value value to set the TemplateId
     */
    public void setTemplateId(String value) {
        setAttributeInternal(TEMPLATEID, value);
    }

    /**
     * Gets the attribute value for ComRecordId, using the alias name ComRecordId.
     * @return the ComRecordId
     */
    public String getComRecordId() {
        return (String)getAttributeInternal(COMRECORDID);
    }

    /**
     * Sets <code>value</code> as the attribute value for ComRecordId.
     * @param value value to set the ComRecordId
     */
    public void setComRecordId(String value) {
        setAttributeInternal(COMRECORDID, value);
    }

    /**
     * Gets the attribute value for Id, using the alias name Id.
     * @return the Id
     */
    public String getId() {
        return (String)getAttributeInternal(ID);
    }

    /**
     * Sets <code>value</code> as the attribute value for Id.
     * @param value value to set the Id
     */
    public void setId(String value) {
        setAttributeInternal(ID, value);
    }

    /**
     * getAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param attrDef the attribute

     * @return the attribute value
     * @throws Exception
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            return AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].get(this);
        }
        return super.getAttrInvokeAccessor(index, attrDef);
    }

    /**
     * setAttrInvokeAccessor: generated method. Do not modify.
     * @param index the index identifying the attribute
     * @param value the value to assign to the attribute
     * @param attrDef the attribute

     * @throws Exception
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        if ((index >= AttributesEnum.firstIndex()) && (index < AttributesEnum.count())) {
            AttributesEnum.staticValues()[index - AttributesEnum.firstIndex()].put(this, value);
            return;
        }
        super.setAttrInvokeAccessor(index, value, attrDef);
    }

    /**
     * @param id key constituent

     * @return a Key object based on given key constituents.
     */
    public static Key createPrimaryKey(String id) {
        return new Key(new Object[]{id});
    }


}
