package team.epm.dms.view.common;

import oracle.jbo.RowSet;
import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Nov 06 19:24:14 CST 2014
// ---------------------------------------------------------------------
public interface DmsRoleView extends ViewObject {
    RowSet fetchEnabledRole();
}
