package team.epm.dms.view.common;

import oracle.jbo.Row;
import oracle.jbo.RowSetIterator;
import oracle.jbo.ViewObject;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Oct 14 17:07:34 CST 2014
// ---------------------------------------------------------------------
public interface DmsUserView extends ViewObject {
    RowSetIterator queryCurUser();
}
